apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: time-service
  template:
    metadata:
      labels:
        app: time-service
    spec:
      containers:
      - name: time-service
        image: kusalthiwanka/time-service:latest
        ports:
        - containerPort: 3030
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
