apiVersion: v1
kind: Service
metadata:
  name: time-service
spec:
  type: NodePort
  selector:
    app: time-service
  ports:
    - protocol: TCP
      port: 3030
      targetPort: 3030
      nodePort: 30030